service: radTwitter

provider:
  name: aws
  runtime: python3.8
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["radTwitterDynamoTable", "Arn" ] }
  environment:
    RADTWITTER_CACHE_TABLE: ${self:custom.tableName}
    RUNNING_SERVERLESS: 1
    RADTWITTER_LINK_CACHE: ${env:RADTWITTER_LINK_CACHE, 'json'}
    RADTWITTER_DATABASE: ${env:RADTWITTER_DATABASE, 'none'}
    RADTWITTER_METHOD: ${env:RADTWITTER_METHOD, 'hybrid'}
    RADTWITTER_COLOR: ${env:RADTWITTER_COLOR, '#43B581'}
    RADTWITTER_APP_NAME: ${env:RADTWITTER_APP_NAME, 'radTwitter'}
    RADTWITTER_REPO: ${env:RADTWITTER_REPO, 'https://github.com/Radiants-DAO/BetterTwitFix'}
    RADTWITTER_URL: ${env:RADTWITTER_URL, 'https://radtwitter.com'}
    RADTWITTER_COMBINATION_METHOD: ${env:RADTWITTER_COMBINATION_METHOD, 'local'}
    RADTWITTER_GIF_CONVERT_API: ${env:RADTWITTER_GIF_CONVERT_API, ''}
    RADTWITTER_WORKAROUND_TOKENS: ${env:RADTWITTER_WORKAROUND_TOKENS, ''}
    RADTWITTER_PROXIES: ${env:RADTWITTER_PROXIES, ''}

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  radTwitterApp:
    handler: wsgi_handler.handler
    url: true
    timeout: 15
    memorySize: 150
    layers:
      - Ref: PythonRequirementsLambdaLayer


custom:
  tableName: 'tweets-table-${self:provider.stage}'
  wsgi:
    app: twitfix.app
  pythonRequirements:
    layer: true
    dockerizePip: false

	
resources:
  Resources:
    radTwitterDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: tweet
            AttributeType: S
        KeySchema:
          -
            AttributeName: tweet
            KeyType: HASH
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true